#ifndef MONEYBIRDAPI_GLOBAL_H
#define MONEYBIRDAPI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MONEYBIRDAPI_LIBRARY)
#  define MONEYBIRDAPISHARED_EXPORT Q_DECL_EXPORT
#else
#  define MONEYBIRDAPISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MONEYBIRDAPI_GLOBAL_H
